- name: docker-machine-config
  hosts: docker-machine
  become: 'yes'
  become_user: 'docker'
  tasks:
    - name: present working directory
      shell: pwd
      
    - name: copy the docker file
      copy: src=Dockerfile.yml dest="./app-files"
      
    - name: change the executable permission of the docker file
      shell: chmod +x ./app-files/Dockerfile
      
    - name: docker image building
      shell: echo admin | sudo -S docker build ./app-files/Dockerfile --tag demo-app ./app-files
      
    - name: push the image to the container registry
      shell: echo admin | sudo -S docker push radhakuna/radha/demo-app
